InvoiceManagementSystem.Web/Areas/Admin/Controllers/ApartmentsController.cs
using InvoiceManagementSystem.Web.Areas.Admin.Models;
using InvoiceManagementSystem.Web.Services.Abstractions;
using Microsoft.AspNetCore.Mvc;

namespace InvoiceManagementSystem.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ApartmentsController : Controller
    {
        readonly IApartmentService _apartmentService;

        public ApartmentsController(IApartmentService apartmentService)
        {
            _apartmentService = apartmentService;
        }

        public IActionResult CreateApartment()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateApartment(CreateApartmentVM apartmentVM)
        {
            await _apartmentService.CreateApartmentAsync(apartmentVM);
            return RedirectToAction(nameof(GetApartments));
        }
        public async Task<IActionResult> UpdateApartment(int apartmentId)
        {
            GetApartmentVM getApartment = await _apartmentService.GetApartmentAsync(apartmentId);
            UpdateApartmentVM updateApartment = new()
            {
                ApartmentNumber = getApartment.ApartmentNumber,
                BlockNumber = getApartment.BlockNumber,
                FloorLocation = getApartment.FloorLocation,
                Id = getApartment.Id,
                Situation = getApartment.Situation,
                Tenant = getApartment.Tenant,
                Type = getApartment.Type
            };
            return View(updateApartment);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateApartment(UpdateApartmentVM apartmentVM)
        {
            await _apartmentService.UpdateApartmentAsync(apartmentVM);
            return RedirectToAction(nameof(GetApartments), "Admin");
        }
        public async Task<IActionResult> GetApartments()
            => View(await _apartmentService.GetAllApartmentsAsync());

        public async Task<IActionResult> DeleteApartment(int apartmentId)
        {
            await _apartmentService.DeleteApartmentAsync(apartmentId);
            return RedirectToAction(nameof(GetApartments));

        }

    }
}

InvoiceManagementSystem.Web/Areas/Admin/Views/Apartments/CreateApartment.cshtml
@{
    ViewData["Title"] = "CreateApartment";
}
@model CreateApartmentVM

<div class="col-xl-10 offset-xl-1 col-xxl-10 offset-xcl-1 col-lg-10 offset-lg-1 ">
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">Horizontal Form</h4>
        </div>
        <div class="card-body">
            <div class="basic-form">
                <form asp-area="Admin" asp-controller="Apartments" asp-action="CreateApartment" method="post">

                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="FloorLocation" asp-for="@Model.FloorLocation"></label>
                            <input id="FloorLocation" type="number" class="form-control" asp-for="@Model.FloorLocation">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="ApartmentNumber" asp-for="@Model.ApartmentNumber"></label>
                            <input id="ApartmentNumber" type="number" class="form-control" asp-for="@Model.ApartmentNumber">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="BlockNumber" asp-for="@Model.BlockNumber"></label>
                            <input id="BlockNumber" type="number" class="form-control" asp-for="@Model.BlockNumber">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="Type" asp-for="@Model.Type"></label>
                            <input id="Type" type="text" class="form-control" asp-for="@Model.Type">
                        </div>


                        <div class="form-group  col-md-6">
                            <div class="form-check mb-2">
                                <input asp-for="@Model.Tenant" type="checkbox" class="form-check-input" id="Tenant" value="" checked="">
                                <label class="form-check-label" for="Tenant" asp-for="@Model.Tenant"></label>
                            </div>
                        </div>
                        <div class="form-group  col-md-6">
                            <div class="form-check mb-2">
                                <input asp-for="@Model.Situation" type="checkbox" class="form-check-input" id="Situation" value="" checked="">
                                <label class="form-check-label" for="Situation" asp-for="@Model.Situation"></label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group col-md-2 offset-md-5 text-center">
                        <input type="submit" class="btn btn-primary" value="Kaydet">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

InvoiceManagementSystem.Web/Areas/Admin/Views/Apartments/GetApartments.cshtml
@{
    ViewData["Title"] = "GetApartments";
}

@model List<GetApartmentVM>
<div class="col-lg-12">
    <div class="row tab-content">
        <div id="list-view" class="tab-pane fade col-lg-12 active show">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Tüm Apartmanlar </h4>
                    <a asp-area="Admin" asp-controller="Apartments" asp-action="CreateApartment" class="btn btn-primary">+ Apartman Ekle</a>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <div id="example3_wrapper" class="dataTables_wrapper no-footer">

                            <table id="example3" class="display dataTable no-footer" style="min-width: 845px" role="grid" aria-describedby="example3_info">
                                <thead>
                                    <tr role="row">
                                        <th class="sorting_asc" tabindex="0" aria-controls="example3" rowspan="1" colspan="1" aria-sort="ascending" aria-label="#: activate to sort column descending" style="width: 54.725px;">#</th>
                                        <th class="sorting" tabindex="0" aria-controls="example3" rowspan="1" colspan="1" style="width: 180.438px;">FloorLocation</th>
                                        <th class="sorting" tabindex="0" aria-controls="example3" rowspan="1" colspan="1" style="width: 171.675px;">BlockNumber</th>
                                        <th class="sorting" tabindex="0" aria-controls="example3" rowspan="1" colspan="1" style="width: 148.688px;">ApartmentNumber</th>
                                        <th class="sorting" tabindex="0" aria-controls="example3" rowspan="1" colspan="1" style="width: 196.962px;">Situation</th>
                                        <th class="sorting" tabindex="0" aria-controls="example3" rowspan="1" colspan="1" style="width: 88.575px;">Tenant</th>
                                        <th class="sorting" tabindex="0" aria-controls="example3" rowspan="1" colspan="1" style="width: 88.575px;">Type</th>
                                        <th class="sorting" tabindex="0" aria-controls="example3" rowspan="1" colspan="1" style="width: 88.575px;">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var apartment in Model)
                                    {
                                        <tr role="row" class="odd">
                                            <td class="sorting_1"><img class="rounded-circle" width="35" src="~/images/profile/small/pic1.jpg" alt=""></td>
                                            <td>@apartment.FloorLocation</td>
                                            <td>@apartment.BlockNumber</td>
                                            <td>@apartment.ApartmentNumber</td>
                                            <td>@apartment.Situation</td>
                                            <td>@apartment.Tenant</td>
                                            <td>@apartment.Type</td>
                                            <td>
                                                <a asp-area="Admin" asp-controller="Apartments" asp-action="UpdateApartment" asp-route-apartmentId="@apartment.Id" class="btn btn-sm btn-primary"><i class="la la-pencil"></i></a>
                                                <a asp-area="Admin" asp-controller="Apartments" asp-action="DeleteApartment" asp-route-apartmentId="@apartment.Id" class="btn btn-sm btn-danger"><i class="la la-trash-o"></i></a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>




<script src="~/vendor/global/global.min.js"></script>
<script src="~/vendor/bootstrap-select/dist/js/bootstrap-select.min.js"></script>
<script src="~/js/custom.min.js"></script>
<script src="~/js/dlabnav-init.js"></script>

<script src="~/vendor/datatables/js/jquery.dataTables.min.js"></script>
<script src="~/js/plugins-init/datatables.init.js"></script>

<script src="~/vendor/svganimation/vivus.min.js"></script>
<script src="~/vendor/svganimation/svg.animation.js"></script>

InvoiceManagementSystem.Web/Areas/Admin/Views/Apartments/UpdateApartment.cshtml
@{
    ViewData["Title"] = "UpdateApartment";
}
@model UpdateApartmentVM
<div class="col-xl-10 offset-xl-1 col-xxl-10 offset-xcl-1 col-lg-10 offset-lg-1 ">
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">Horizontal Form</h4>
        </div>
        <div class="card-body">
            <div class="basic-form">
                <form asp-area="Admin" asp-controller="Apartments" asp-action="UpdateApartment" method="post">
                  
                    <div class="form-row">
                        <input type="hidden" asp-for="@Model.Id" />
                        <div class="form-group col-md-6">
                            <label for="FloorLocation" asp-for="@Model.FloorLocation"></label>
                            <input id="FloorLocation" type="number" class="form-control" asp-for="@Model.FloorLocation">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="ApartmentNumber" asp-for="@Model.ApartmentNumber"></label>
                            <input id="ApartmentNumber" type="number" class="form-control" asp-for="@Model.ApartmentNumber">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="BlockNumber" asp-for="@Model.BlockNumber"></label>
                            <input id="BlockNumber" type="number" class="form-control" asp-for="@Model.BlockNumber">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="Type" asp-for="@Model.Type"></label>
                            <input id="Type" type="text" class="form-control" asp-for="@Model.Type">
                        </div>

                        <div class="form-group  col-md-6">
                            <div class="form-check mb-2">
                                <input asp-for="@Model.Tenant" type="checkbox" class="form-check-input" id="Tenant" value="" checked="">
                                <label class="form-check-label" for="Tenant" asp-for="@Model.Tenant"></label>
                            </div>
                        </div>
                        <div class="form-group  col-md-6">
                            <div class="form-check mb-2">
                                <input asp-for="@Model.Situation" type="checkbox" class="form-check-input" id="Situation" value="" checked="">
                                <label class="form-check-label" for="Situation" asp-for="@Model.Situation"></label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group col-md-2 offset-md-5 text-center">
                        <input type="submit" class="btn btn-primary" value="Kaydet">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>