InvoiceManagementSystem.Web/Areas/Admin/Controllers/UsersController.cs
using InvoiceManagementSystem.Web.Areas.Admin.Models;
using InvoiceManagementSystem.Web.Services.Abstractions;
using Microsoft.AspNetCore.Mvc;

namespace InvoiceManagementSystem.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UsersController : Controller
    {
        readonly IUserService _userService;

        public UsersController(IUserService userService)
        {
            _userService = userService;
        }

        public IActionResult CreateUser()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateUser(CreateUserVM userVM)
        {
            await _userService.CreateUserAsync(userVM);
            return RedirectToAction(nameof(GetUsers), "Admin");
        }
        public async Task<IActionResult> UpdateUser(string userId)
        {
            GetUserVM getUser = await _userService.GetUserAsync(userId);
            UpdateUserVM updateUser = new()
            {
                CarPlateNumber = getUser.CarPlateNumber,
                Email = getUser.Email,
                Id = getUser.Id,
                Name = getUser.Name,
                PhoneNumber = getUser.PhoneNumber,
                Surname = getUser.Surname,
                TCNo = getUser.TCNo,
                UserName = getUser.UserName
            };
            return View(updateUser);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateUser(UpdateUserVM userVM)
        {
            await _userService.UpdateUserAsync(userVM);
            return RedirectToAction(nameof(GetUsers), "Admin");
        }
        public async Task<IActionResult> GetUsers()
            => View(await _userService.GetAllUsersAsync());

        public async Task<IActionResult> DeleteUser(string userId)
        {
            await _userService.DeleteUserAsync(userId);
            return RedirectToAction(nameof(GetUsers));

        }

        public async Task<IActionResult> GetDebtList()
           => View(await _userService.GetDebtListAsync());
    }
}

InvoiceManagementSystem.Web/Controllers/InvoicesController.cs
using InvoiceManagementSystem.Web.Services.Abstractions;
using Microsoft.AspNetCore.Mvc;

namespace InvoiceManagementSystem.Web.Controllers
{
    public class InvoicesController : Controller
    {
        readonly IInvoiceService _invoiceService;

        public InvoicesController(IInvoiceService invoiceService)
        {
            _invoiceService = invoiceService;
        }

        public async Task<IActionResult> GetInvoices()
            => View(await _invoiceService.GetInvoicesAsync("hasan"));
        public async Task<IActionResult> GetInvoice(int invoiceId)
           => View(await _invoiceService.GetInvoiceAsync(invoiceId));
    }
}

InvoiceManagementSystem.Web/Controllers/MessagesController.cs
using InvoiceManagementSystem.Web.Models;
using InvoiceManagementSystem.Web.Services.Abstractions;
using Microsoft.AspNetCore.Mvc;

namespace InvoiceManagementSystem.Web.Controllers
{
    public class MessagesController : Controller
    {
        readonly IMessageService _messageService;

        public MessagesController(IMessageService messageService)
        {
            _messageService = messageService;
        }

        public IActionResult SendMessage()
           => View();
        [HttpPost]
        public async Task<IActionResult> SendMessage(CreateMessageVM createMessageVM)
        {
            createMessageVM.UserName = "hasan";
            await _messageService.SendMessageAsync(createMessageVM);
            return RedirectToAction(nameof(HomeController.Index),"Home");
        }
    }
}

InvoiceManagementSystem.Web/Controllers/PaymentsController.cs
using InvoiceManagementSystem.Web.Models;
using InvoiceManagementSystem.Web.Services.Abstractions;
using Microsoft.AspNetCore.Mvc;

namespace InvoiceManagementSystem.Web.Controllers
{
    public class PaymentsController : Controller
    {
        readonly IPaymentService _paymentService;

        public PaymentsController(IPaymentService paymentService)
        {
            _paymentService = paymentService;
        }

        public IActionResult Payment(int invoiceId, string invoicePrice)
        {
            TempData["InvoicePrice"] = invoicePrice;
            TempData["InvoicePrice1"] = invoicePrice;
            TempData["InvoiceId"] = invoiceId;

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Payment(PaymentVM payment)
        {
            payment.Price = decimal.Parse(TempData["InvoicePrice1"].ToString());
            await _paymentService.PaymentAsync(payment.CreditCard, (int)TempData["InvoiceId"]);
            return RedirectToAction(nameof(Index));
        }
    }
}

InvoiceManagementSystem.Web/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="keywords" content="" />
    <meta name="author" content="" />
    <meta name="robots" content="" />
    <meta name="format-detection" content="telephone=no">
    <link rel="icon" href="~/images/favicon.ico" type="image/x-icon" />
    <link rel="shortcut icon" type="image/x-icon" href="~/images/favicon.png" />
    <title>@ViewData["Title"] - Fatura Yönetim Sistemi</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="~/vendor/bootstrap-select/dist/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/skin.css">
    <link href="~/vendor/datatables/css/jquery.dataTables.min.css" rel="stylesheet">
</head>
<body>
    <div id="preloader">
        <div class="sk-three-bounce">
            <div class="sk-child sk-bounce1"></div>
            <div class="sk-child sk-bounce2"></div>
            <div class="sk-child sk-bounce3"></div>
        </div>
    </div>
    <div id="main-wrapper">
        <div class="nav-header">
            <a href="index.html" class="brand-logo">
                <img class="logo-abbr" src="~/images/logo-white-2.png" alt="">
                <img class="logo-compact" src="~/images/logo-text-white.png" alt="">
                <img class="brand-title" src="~/images/logo-text-white.png" alt="">
            </a>
            <div class="nav-control">
                <div class="hamburger">
                    <span class="line"></span><span class="line"></span><span class="line"></span>
                </div>
            </div>
        </div>
        <div class="header">
            <div class="header-content">
                <nav class="navbar navbar-expand">
                    <div class="collapse navbar-collapse justify-content-between">
                        <div class="header-left">
                        </div>
                        <ul class="navbar-nav header-right">
                            <li class="nav-item dropdown notification_dropdown">
                                <a class="nav-link bell ai-icon" href="#" role="button" data-toggle="dropdown">
                                    <svg id="icon-user" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bell">
                                        <path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"></path>
                                        <path d="M13.73 21a2 2 0 0 1-3.46 0"></path>
                                    </svg>
                                    <div class="pulse-css"></div>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <ul class="list-unstyled">
                                        <li class="media dropdown-item">
                                            <span class="success"><i class="ti-user"></i></span>
                                            <div class="media-body">
                                                <a href="#">
                                                    <p>
                                                        <strong>Martin</strong> has added a <strong>customer</strong> Successfully
                                                    </p>
                                                </a>
                                            </div>
                                            <span class="notify-time">3:20 am</span>
                                        </li>

                                    </ul>
                                    <a class="all-notification" href="#">
                                        Tüm Bildirimleri Gör <i class="ti-arrow-right"></i>
                                    </a>
                                </div>
                            </li>
                            <li class="nav-item dropdown header-profile">
                                <a class="nav-link" href="#" role="button" data-toggle="dropdown">
                                    <img src="~/images/profile/education/pic1.jpg" width="20" alt="" />
                                </a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a href="./app-profile.html" class="dropdown-item ai-icon">
                                        <svg id="icon-user1" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>
                                        <span class="ml-2">Profil </span>
                                    </a>
                                    <a asp-area="Admin" asp-controller="Messages" asp-action="GetMessages" class="dropdown-item ai-icon">
                                        <svg id="icon-inbox" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-mail"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path><polyline points="22,6 12,13 2,6"></polyline></svg>
                                        <span class="ml-2">Mesajlar </span>
                                    </a>
                                    <a href="./page-login.html" class="dropdown-item ai-icon">
                                        <svg id="icon-logout" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-log-out"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path><polyline points="16 17 21 12 16 7"></polyline><line x1="21" y1="12" x2="9" y2="12"></line></svg>
                                        <span class="ml-2">Çıkış Yap </span>
                                    </a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
        <div class="dlabnav">
            <div class="dlabnav-scroll">
                <ul class="metismenu" id="menu">
                    <li class="nav-label first">Ana Menü</li>
                    <li>
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="la la-users"></i>
                            <span class="nav-text">Kişiler</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a asp-area="Admin" asp-controller="Users" asp-action="GetUsers">Kişileri Listele</a></li>
                            <li><a asp-area="Admin" asp-controller="Users" asp-action="CreateUser">Kişi Ekle</a></li>
                        </ul>
                    </li>
                    <li>
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="la la-home"></i>
                            <span class="nav-text">Daireler</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a asp-area="Admin" asp-controller="Apartments" asp-action="GetApartments">Daireleri Listele</a></li>
                            <li><a asp-area="Admin" asp-controller="Apartments" asp-action="CreateApartment">Daire Ekle</a></li>
                        </ul>
                    </li>
                    <li>
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="la la-users"></i>
                            <span class="nav-text">Faturalar</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a asp-area="Admin" asp-controller="Invoices" asp-action="CreateInvoice">Fatura Oluştur</a></li>
                            <li><a asp-area="Admin" asp-controller="Payments" asp-action="GetPayments">Ödenmiş Faturalar</a></li>
                            <li><a asp-area="Admin" asp-controller="Users" asp-action="GetDebtList">Borç Listesi</a></li>
                        </ul>
                    </li>


                </ul>
            </div>
        </div>
        <div class="content-body">
            <div class="container-fluid">

                <div class="row">
                        @RenderBody()
                </div>
            </div>
        </div>
        <div class="footer">
            <div class="copyright">
                <p>Copyright © Designed &amp; Developed by <a href="http://dexignlab.com/" target="_blank">DexignLab</a> 2021</p>
            </div>
        </div>
    </div>
    <script src="~/vendor/global/global.min.js"></script>
    <script src="~/vendor/bootstrap-select/dist/js/bootstrap-select.min.js"></script>
    <script src="~/js/custom.min.js"></script>
    <script src="~/vendor/raphael/raphael.min.js"></script>
    <script src="~/vendor/morris/morris.min.js"></script>
    <script src="~/vendor/peity/jquery.peity.min.js"></script>
    <script src="~/js/dashboard/dashboard-2.js"></script>
    <script src="~/vendor/svganimation/vivus.min.js"></script>
    <script src="~/vendor/svganimation/svg.animation.js"></script>
</body>
</html>